### ISSUE TITLE
spicetify-creator fails on local build; sources mismatch npm

### ISSUE THREAD

**Issue by kiprasmel** [FlafyDev/spicetify-creator#22]
hello. i'm trying to build spicetify-creator locally, but without much luck.

```sh
git clone https://github.com/spicetify/spicetify-creator
cd spicetify-creator
yarn
cd packages/spicetify-creator
yarn
yarn build
ls dist
# => buildCustomApp.js       buildExtension.js       helpers                 index.js                scripts.js

diff -r dist dist-npm
# => Only in dist-npm: temp
```

1. this mismatches what's published on npm (on npm, there's a dist/temp folder for some reason)
2. when i try to run the built CLI, it doesn't work:

```sh
node dist/index.js

node:fs:453
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open './src/settings.json'
    at Object.readFileSync (node:fs:453:20)
    at build (/Users/kipras/infra/local/spicetify/spicetify-creator/packages/spicetify-creator/dist/scripts.js:19:46)
    at Object.<anonymous> (/Users/kipras/infra/local/spicetify/spicetify-creator/packages/spicetify-creator/dist/index.js:6:21)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './src/settings.json'
}

Node.js v20.11.1
```

seems like an issue with the `inDirectory` thing

**Comment by kiprasmel** [comment]
whoop, nevermind, CLI works fine, just needed to use it inside a buildable dir.
